name: prepare

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
  main:
    name: Flutter ${{ matrix.flutter-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        flutter-version: ["3.27.x"]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ matrix.flutter-version }}

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: flutter pub get
        run: flutter pub get

      - name: Build example app
        working-directory: example
        run: flutter build apk --debug

      - name: dart format
        run: dart format --set-exit-if-changed .

      - name: flutter analyze
        run: flutter analyze --no-fatal-infos

      - name: flutter test
        run: flutter test

      - name: ktlint check
        working-directory: example/android
        run: ./gradlew flutter_downloader:ktlintCheck

      - name: flutter pub get (example app)
        working-directory: ./example
        run: flutter pub get

      - name: flutter format (example app)
        working-directory: ./example
        run: dart format --set-exit-if-changed .

      - name: flutter analyze (example app)
        working-directory: ./example
        run: flutter analyze --no-fatal-infos

      - name: flutter test (example app)
        working-directory: ./example
        run: flutter test

      - name: Dry run pub publish
        # We don't want it to fail the CI, it's just to see how would `pub publish` behave.
        run: dart pub publish --dry-run || true
