name: publish

on:
  push:
    tags: ["v*"]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.17.0

      - name: Download pub.dev credentials
        env:
          CREDENTIALS: ${{ secrets.PUB_DEV_CREDENTIALS }}
        run: |
          mkdir -p ~/.pub-cache
          echo $CREDENTIALS > ~/.pub-cache/credentials.json

      - name: Publish
        run: dart pub publish -f
